Question:
Create a 3D array of shape (3, 4, 5) filled with random integers between 1 and 100.
Perform the following tasks:

Replace all elements greater than the mean of the entire array with 0.

Calculate the sum along axis=1 (i.e., sum across the 5 columns in each depth slice).

Extract a new 2D array that contains only the first and last columns from each row of each depth slice.

In [3]:
import numpy as np
arr3d = np.random.randint(1,101,size = (3,4,5))
print(f"3D array:\n {arr3d}")

3D array:
 [[[12 25 83 84 51]
  [93 74 85 12 64]
  [18 34  9 71  5]
  [75 64  1 33 17]]

 [[ 1 32 27 70 70]
  [26 38 71 10 75]
  [73  1 68 59  8]
  [94  2  7 66 96]]

 [[37 21 76 67 39]
  [39 73 95 70 52]
  [70 12 80 70 98]
  [48 18 84 18  7]]]


In [16]:
m = np.mean(arr3d)
print(f"Mean:{m}")
u = np.where(arr3d>m,0,arr3d)
print(f"replacing element greater than mean with 0:\n{u}")

Mean:47.96666666666667
replacing element greater than mean with 0:
[[[12 25  0  0  0]
  [ 0  0  0 12  0]
  [18 34  9  0  5]
  [ 0  0  1 33 17]]

 [[ 1 32 27  0  0]
  [26 38  0 10  0]
  [ 0  1  0  0  8]
  [ 0  2  7  0  0]]

 [[37 21  0  0 39]
  [39  0  0  0  0]
  [ 0 12  0  0  0]
  [ 0 18  0 18  7]]]


In [ ]:
x=arr3d.sum(axis=1)
print(f"sum of each columns:\n{x}")

sum of each columns:
[[198 197 178 200 137]
 [194  73 173 205 249]
 [194 124 335 225 196]]


In [14]:
# y = arr3d[:,:,[0,-1]]
# print(y)
a2d = arr3d.reshape(12,5)
print(f"Converting into 2d array which contains first & last column of 3d array:\n{a2d[:,[0,-1]]}")

Converting into 2d array which contains first & last column of 3d array:
[[12 51]
 [93 64]
 [18  5]
 [75 17]
 [ 1 70]
 [26 75]
 [73  8]
 [94 96]
 [37 39]
 [39 52]
 [70 98]
 [48  7]]


Create a NumPy array of numbers from 10 to 50.

Generate a 3×3 identity matrix.

Create a NumPy array of 10 random integers between 1 and 100.

Find the maximum and minimum of an array.

Reshape a 1D array of 12 elements into a 3×4 matrix.

Create an array of all even numbers between 50 and 100.

Given an array [1,2,3,4,5], compute the square of each element.

Create a 5×5 array of random numbers and find its mean.

Find the index of the maximum element in [10, 20, 50, 40, 30].

Create two arrays and perform element-wise addition, subtraction, multiplication, and division.


Create a NumPy array of numbers from 10 to 50.

In [18]:
import numpy as np
x = np.arange(10,51)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


Generate a 3×3 identity matrix.

In [22]:
x = np.identity(3, dtype= int)

print(f"Identity matrix:\n{x}")

Identity matrix:
[[1 0 0]
 [0 1 0]
 [0 0 1]]


Create a NumPy array of 10 random integers between 1 and 100.

In [30]:
y = np.random.randint(1,101,size=10)
print(y)

[ 75  53   7  31   4  49  32 100  44  18]


Find the maximum and minimum of an array

In [40]:
array = np.arange(5,20)
print(array)
y=array.max()
print(f"max value:{y}")
x = array.min()
print(f"min value:{x}")

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
max value:19
min value:5


Reshape a 1D array of 12 elements into a 3×4 matrix.

In [41]:
y = np.arange(1,13)
print(f"array:{y}")
x= y.reshape(3,4)
print(f"reshaped:\n{x}")

array:[ 1  2  3  4  5  6  7  8  9 10 11 12]
reshaped:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Create an array of all even numbers between 50 and 100.

In [45]:
y= np.arange(50,101,2)
print(y)


[ 50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80  82  84
  86  88  90  92  94  96  98 100]


Given an array [1,2,3,4,5], compute the square of each element.

In [47]:
arr =[1,2,3,4,5]
sq= np.power(arr,2)
print(sq)

[ 1  4  9 16 25]


Create a 5×5 array of random numbers and find its mean.

In [50]:
x = np.random.randint(1,15,size=(5,5))
print(x)
print(f"mean:{np.mean(x)}")

[[ 1 13  2  7 11]
 [ 3 14  6  9 12]
 [13  7  5 10  3]
 [ 7 11  9  6  9]
 [ 2  9 13  6  9]]
mean:7.88


Find the index of the maximum element in [10, 20, 50, 40, 30].

In [56]:
x = [10,20,50,40,30]
y = np.argmax(x)
print(y)

2


Create two arrays and perform element-wise addition, subtraction, multiplication, and division.

In [70]:
arr1 = np.arange(1,6)
arr2 = np.arange(11,16)
print(arr1)
print(arr2)
print(f"sum:{np.add(arr1,arr2)}\n")
print(f"subtracting arr1 & arr2 : {np.subtract(arr1,arr2)}\nsubtracting arr2 & arr1: {np.subtract(arr2,arr1)}\n")
print(f"Multiplication:{np.multiply(arr1,arr2)}\n")
print(f"Division of arr1 & arr2 : {np.divide(arr1,arr2)}\ndivision of arr2 & arr1: {np.divide(arr2,arr1)}\n")


[1 2 3 4 5]
[11 12 13 14 15]
sum:[12 14 16 18 20]

subtracting arr1 & arr2 : [-10 -10 -10 -10 -10]
subtracting arr2 & arr1: [10 10 10 10 10]

Multiplication:[11 24 39 56 75]

Division of arr1 & arr2 : [0.09090909 0.16666667 0.23076923 0.28571429 0.33333333]
division of arr2 & arr1: [11.          6.          4.33333333  3.5         3.        ]

