In [2]:
import numpy as np
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [3]:
nmp = np.arange(1,51)
arr = nmp.reshape(5,2,5)
print(arr)
print(f"index of 3d :{arr[1,0,3]}")
print(f"slice of 3d:{arr[2:,0:,3:]}")
print()
arr = nmp.reshape(5,10)
print(f"array of 2D:{arr}")
print(f"Indexing an array of 2D:{arr[3,5]}")
print(f"slicing an array of 2D:{arr[0:3,2:7]}")


[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]

 [[31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]]]
index of 3d :14
slice of 3d:[[[24 25]
  [29 30]]

 [[34 35]
  [39 40]]

 [[44 45]
  [49 50]]]

array of 2D:[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]
Indexing an array of 2D:36
slicing an array of 2D:[[ 3  4  5  6  7]
 [13 14 15 16 17]
 [23 24 25 26 27]]


full 

In [4]:
xy = np.full(shape = (4,5), fill_value= 88)
print(f"using full :{xy}")
print(f"using flatten:{xy.flatten()}")

using full :[[88 88 88 88 88]
 [88 88 88 88 88]
 [88 88 88 88 88]
 [88 88 88 88 88]]
using flatten:[88 88 88 88 88 88 88 88 88 88 88 88 88 88 88 88 88 88 88 88]


np.matmul is used to multiply the arrays in matrix form

Dot Product

If the array is 2d, dot product gives matrix multiplication.
If the array is 1d,dot product sums the vectorized multiplication.

use: np.dot  or  @ 

Transpose
Interchanging the rows and column is transpose.

Two ways to perform transpose operations:
1. np.transpose
2. array_name .T


Identity Matrix
Diagonal are 1 and other are 0. It must be a square matrix where rows = column.
cmd: np.identity(4) here, 4 is no.of rows and columns

np.eye also used to make matrix same as identity matrix, where we can change rows and columns.
eg: np.eye(N:5,M:3,k:2) where, N: rows, M: columns, K: to start diagonal as 1.





Use more syntax

np.where(condition,value_if_true,value_if_false)
np.any(condition) here, any one element satisfy codition gives result true.
np.all(condition) here, all element must satisfy condition otherwise result is false.


pandas

data structure are: series and data frame 